apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-api
  labels:
    app: event-api
spec:
  replicas: {{ .Values.eventApi.replicaCount }}
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      containers:
        - name: event-api
          image: "{{ .Values.eventApi.image.repository }}:{{ .Values.eventApi.image.tag }}"
          imagePullPolicy: {{ .Values.eventApi.image.pullPolicy }}
          env:
            {{- range .Values.eventApi.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.eventApi.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-event-api
  labels:
    app: event-api
spec:
  type: {{ .Values.eventApi.service.type }}
  ports:
    - port: {{ .Values.eventApi.service.port }}
      targetPort: {{ .Values.eventApi.service.port }}
      protocol: TCP
      name: http
  selector:
    app: event-api
---
{{- if .Values.eventApi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-event-api
  labels:
    app: event-api
spec:
  ingressClassName: {{ .Values.eventApi.ingress.className }}
  rules:
    {{- range .Values.eventApi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-event-api
                port:
                  number: {{ $.Values.eventApi.service.port }}
          {{- end }}
    {{- end }}
{{- end }}