apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  type: NodePort
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 9102
      targetPort: 9102
      nodePort: 30001
      name: metrics