apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-streaming-platform-service-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka-producer
  endpoints:
    - port: metrics
      path: "/metrics"
      interval: 30s
